name: PHP-Insights-Run

on:
  # php-cs-fixer.ymlが実行されたときに連動して実行
  workflow_run:
    workflows:
      - "PHP-CS-Fixer"
    types:
      - completed

jobs:
  php-insights-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read #読み取りのみ

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist

      - name: Run PHP Insights
        run: |
          php artisan insights -n --ansi --format=json > phpinsights.json || true

      # PR番号とPHP Insightsの実行結果を別ディレクトリに保存
      - name: Save PR Number
        env:
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: |
          mkdir -p ./insights-result
          if [ -z "$PR_NUMBER" ]; then
            echo "No pull request associated with this workflow run."
            exit 1
          fi
          echo "$PR_NUMBER" > ./insights-result/pr-number.txt
          cp phpinsights.json ./insights-result/phpinsights.json

      # アーティファクトとして保存してphp-insights-report.ymlから取得できるようにしておく
      - name: Upload PHP Insights Results
        uses: actions/upload-artifact@v4
        with:
          name: insights-results
          path: ./insights-result/
